### ISSUE TITLE
Propose moving this under the graphql org?

### ISSUE THREAD

**Issue by gjtorikian** [skevy/graphiql-app#114]
I don't really have time to maintain this app very much, and it seems like there are quite a few bugs and feature requests. @skevy if I chat with Lee Byron about it would you be opposed to moving this under the https://github.com/graphql org? I imagine it'll gain more visibility and attention there.

**Comment by skevy** [comment]
Not at all. Happy to do that!

**Comment by gjtorikian** [comment]
@leebyron Sorry for the direct ping -- I think Kyle might've reached out to you too about this -- is there any interest in moving this under the official `graphql` org on GitHub?

**Comment by gjtorikian** [comment]
Cool, I get to be that guy who pings multiple people:

@jspahrsummers (hi!) @AGS- @dwwoelfel @jjergus @robzhu @wincent Would any one have interest in transferring this project into [the main GraphQL](https://github.com/graphql) organization? Thanks!

**Comment by Aowe047** [comment]
> I don't really have time to maintain this app very much, and it seems like there are quite a few bugs and feature requests. @skevy if I chat with Lee Byron about it would you be opposed to moving this under the https://github.com/graphql org? I imagine it'll gain more visibility and attention there.

**Comment by AmberHussle19** [comment]
> Cool, I get to be that guy who pings multiple people:
> 
> @jspahrsummers (hi!) @AGS- @dwwoelfel @jjergus @robzhu @wincent Would any one have interest in transferring this project into [the main GraphQL](https://github.com/graphql) organization? Thanks!

**Comment by leebyron** [comment]
Since the last time this was discussed above, we've formed the GraphQL Foundation which has a much better repo management situation (as opposed to relying on Facebook/Meta internal tools)

However an important note is that moving it into the foundation does not bring maintenance support. We have a criteria that projects that want to move into the GraphQL foundation should have active maintainers. If we have volunteers for this one, we can consider it
