### ISSUE TITLE
Allow override of User-Agent header?

### ISSUE THREAD

**Issue by rmosolgo** [skevy/graphiql-app#62]
Hey, thanks for the great app! It's been really really useful. 

I'm in an interesting spot now -- I'm trying to test an API whose behavior depends on the incoming `User-Agent` header. 

I tried setting it in the headers box, but it looks like it wasn't applied: 

![image](https://cloud.githubusercontent.com/assets/2231765/26600666/edb2e010-454a-11e7-8997-51331b41c6b7.png)

![image](https://cloud.githubusercontent.com/assets/2231765/26600681/f94682f6-454a-11e7-9d4b-1c823fe84069.png)

Would it be possible to accept user-agent overrides here? Thanks!

**Comment by skevy** [comment]
Sure. Want to send a PR

**Comment by intellix** [comment]
https://github.com/skevy/graphiql-app/pull/66 adds support for Origin header to get around CORS and you can also send the User-Agent header there too. If you provide it with fetch then it won't get sent at all. 

I'm guessing some stuff needs refactoring to send requests via Electron instead of Fetch
